/* ExploreUP Priority 5 — smart travel layer. Safe, optional enhancement; does not replace core planner. */
(function(){
'use strict';
if(window.__exploreUpPriority5Loaded)return; window.__exploreUpPriority5Loaded=true;
const S=window.localStorage;
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const get=(k,d)=>{try{return JSON.parse(S.getItem(k)||JSON.stringify(d))}catch(e){return d}};
const put=(k,v)=>{try{S.setItem(k,JSON.stringify(v))}catch(e){}};
const tripKey='exploreup_priority5_trip_v1';
const savedKey='exploreup_priority5_saved_plan_v1';
const eventData=[
 ['January','Khichdi Mela','Prayagraj / eastern UP','Seasonal cultural visit'],
 ['February','Taj Mahotsav','Agra','Heritage, crafts and culture'],
 ['March','Holi celebrations','Across Uttar Pradesh','Check local dates and crowd conditions'],
 ['April','Ram Navami period','Ayodhya','Religious/cultural travel'],
 ['May','Buddha Purnima period','Sarnath / Varanasi','Heritage and spiritual travel'],
 ['June','Ganga Dashahara period','Varanasi / river cities','Check local schedules'],
 ['July','Sawan season','Varanasi / major Shiva sites','Expect high visitor activity'],
 ['August','Janmashtami period','Mathura–Vrindavan','Check official event schedules'],
 ['September','Ramleela season begins','Varanasi / regional centres','Dates vary by location'],
 ['October','Dussehra season','Across Uttar Pradesh','Local programmes vary'],
 ['November','Dev Deepawali period','Varanasi','Check official dates before travel'],
 ['December','Winter heritage season','Across Uttar Pradesh','Generally suited to outdoor sightseeing']
];
const monthIndex=m=>{const s=String(m||'');const match=/^(?:\d{4}-)?(\d{1,2})(?:-\d{1,2})?$/.exec(s);if(match)return Math.max(0,Math.min(11,Number(match[1])-1));const d=new Date(s);return Number.isNaN(d.getTime())?new Date().getMonth():d.getMonth()};
const weatherText=code=>{if(code===0)return 'Clear';if(code<=3)return 'Partly cloudy';if(code<=48)return 'Fog / mist possible';if(code<=67)return 'Rain possible';if(code<=77)return 'Snow conditions';if(code<=82)return 'Rain showers';return 'Thunderstorm risk';};
function injectStyle(){if(document.getElementById('exploreup-p5-style'))return;const s=document.createElement('style');s.id='exploreup-p5-style';s.textContent='.p5box{margin-top:14px;border:1px solid #dfe7f1;border-radius:16px;padding:14px;background:#f7faff}.p5grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.p5grid label{font-size:12px;font-weight:750}.p5grid input,.p5grid select{width:100%;margin-top:5px;padding:10px;border:1px solid #d7e1ed;border-radius:10px;background:#fff;color:inherit;box-sizing:border-box}.p5actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.p5btn{border:1px solid #cfdbea;background:#fff;color:#17304f;border-radius:999px;padding:9px 12px;font-weight:800;cursor:pointer}.p5btn.primary{background:#ffb51b;border-color:#ffb51b}.p5out{margin-top:10px}.p5card{border:1px solid #dfe7f1;background:#fff;border-radius:12px;padding:11px;margin-top:8px}.p5muted{color:#60708a;font-size:12px}.p5chips{display:flex;flex-wrap:wrap;gap:6px;margin-top:7px}.p5chip{padding:6px 9px;border-radius:999px;background:#eef5ff;color:#145eaf;font-size:11px;font-weight:800}@media(max-width:650px){.p5grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function findCity(name){const list=window.cities||[];return list.find(c=>String(c.name).toLowerCase()===String(name).toLowerCase())||list.find(c=>String(c.name).toLowerCase().includes(String(name).toLowerCase()));}
function prefs(){return [...document.querySelectorAll('#planPrefs input:checked')].map(x=>x.value)}
function savedPlaces(){let a=get('exploreup_favs',[]);return Array.isArray(a)?a:[]}
function buildRoute(dest,days,style){const c=findCity(dest),k=c&&window.aryaKnowledge?window.aryaKnowledge[c.name]||{}:{};const places=String(k.places||c?.places||'Main local attractions').split(',').map(x=>x.trim()).filter(Boolean);const food=String(k.food||c?.food||'Local cuisine').split(',').map(x=>x.trim()).filter(Boolean);const p=prefs();const focus=style==='food'?'food':style==='nature'?'nature':style==='heritage'?'heritage':style==='religion'?'religion':style==='shopping'?'shopping':style==='photography'?'photography':style==='family'?'family':'balanced';const out=[];for(let d=0;d<days;d++){const a=places[(d*2)%Math.max(1,places.length)]||'Top attraction';const b=places[(d*2+1)%Math.max(1,places.length)]||'Nearby attraction';const f=food[d%Math.max(1,food.length)]||'Local food stop';let eve=focus==='shopping'?'Local market / shopping':focus==='nature'?'Park, riverfront or relaxed outdoor stop':focus==='food'?'Food-focused evening':focus==='photography'?'Golden-hour photography stop':'Cultural stop / relaxed evening';out.push({day:d+1,morning:a,afternoon:b,food:f,evening:eve});}return out}
function renderEnhancedPlan(){const r=document.getElementById('planResult'),dest=document.getElementById('planDestination')?.value.trim();if(!r||!dest)return;const days=Math.max(1,Math.min(7,Number(document.getElementById('planDays')?.value||3)));const style=document.getElementById('planStyle')?.value||'balanced';const route=buildRoute(dest,days,style);const start=document.getElementById('p5Date')?.value||'';r.querySelectorAll('.p5box').forEach(x=>x.remove());let html='<div class="p5box"><b>🧠 Priority 5 Smart Layer</b><div class="p5muted">Refined day flow, saved places, event timing and optional live weather. Route order is a practical suggestion, not GPS navigation.</div>';route.forEach(d=>{html+='<div class="p5card"><b>Day '+d.day+'</b><div>🌅 Morning — '+esc(d.morning)+'</div><div>☀️ Afternoon — '+esc(d.afternoon)+'</div><div>🍽️ Food — '+esc(d.food)+'</div><div>🌆 Evening — '+esc(d.evening)+'</div></div>'});const fav=savedPlaces();if(fav.length)html+='<div class="p5card"><b>❤️ Saved places</b><div class="p5chips">'+fav.slice(0,12).map(x=>'<span class="p5chip">'+esc(x)+'</span>').join('')+'</div></div>';if(start){const ev=eventData[monthIndex(start)];if(ev)html+='<div class="p5card"><b>🎉 Seasonal event guide</b><div><b>'+esc(ev[1])+'</b> — '+esc(ev[2])+'</div><div class="p5muted">'+esc(ev[3])+'. Exact dates/schedules can vary.</div></div>'}html+='<div class="p5actions"><button class="p5btn primary" type="button" onclick="p5SavePlan()">💾 Save Plan</button><button class="p5btn" type="button" onclick="p5SharePlan()">↗ Share Plan</button></div></div>';r.insertAdjacentHTML('beforeend',html)}
async function weather(){const dest=document.getElementById('planDestination')?.value.trim(),out=document.getElementById('p5Weather');if(!out||!dest)return;out.textContent='Checking live weather…';try{if(!navigator.onLine)throw new Error('offline');const g=await fetch('https://geocoding-api.open-meteo.com/v1/search?name='+encodeURIComponent(dest)+'&count=1&language=en&format=json').then(r=>r.json());const x=g.results?.[0];if(!x)throw new Error('not found');const d=await fetch('https://api.open-meteo.com/v1/forecast?latitude='+x.latitude+'&longitude='+x.longitude+'&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&forecast_days=7&timezone=auto').then(r=>r.json());const rows=(d.daily?.time||[]).slice(0,7).map((date,i)=>'<div class="p5card"><b>'+date+'</b> · '+weatherText(d.daily.weather_code[i])+' · '+Math.round(d.daily.temperature_2m_min[i])+'–'+Math.round(d.daily.temperature_2m_max[i])+'°C · rain chance '+(d.daily.precipitation_probability_max?.[i]??0)+'%</div>').join('');out.innerHTML='<div class="p5card"><b>🌦️ Live 7-day weather near '+esc(x.name)+'</b>'+rows+'<div class="p5muted">Live forecast is optional and needs internet. It is not a guarantee for future travel dates.</div></div>'}catch(e){out.innerHTML='<div class="p5card"><b>🌦️ Weather fallback</b><div class="p5muted">Live weather is unavailable right now. Use the seasonal/event guide and check the forecast again closer to travel.</div></div>'}}
function p5SavePlan(){const r=document.getElementById('planResult');if(!r)return;put(savedKey,{destination:document.getElementById('planDestination')?.value||'',days:document.getElementById('planDays')?.value||'3',savedAt:new Date().toISOString(),html:r.innerHTML});const s=document.getElementById('planStatus');if(s)s.textContent='💾 Plan saved on this device.'}
async function p5SharePlan(){const dest=document.getElementById('planDestination')?.value||'ExploreUP trip',r=document.getElementById('planResult'),text=(r?.innerText||'ExploreUP trip plan').slice(0,5000);try{if(navigator.share){await navigator.share({title:'ExploreUP — '+dest,text})}else{await navigator.clipboard.writeText(text);alert('Trip plan copied!')}}catch(e){try{await navigator.clipboard.writeText(text);alert('Trip plan copied!')}catch(_){alert('Trip plan ready to share.')}}}
function mount(){injectStyle();const modal=document.getElementById('planMakerModal'),body=modal?.querySelector('.plan-body');if(!body||document.getElementById('p5Controls'))return;const box=document.createElement('div');box.className='p5box';box.id='p5Controls';box.innerHTML='<b>🚀 Smart Travel Upgrade</b><div class="p5muted">Make the existing Arya plan more useful without changing the original planner.</div><div class="p5grid"><label>Start date<input id="p5Date" type="date"></label><label>Weather check<select id="p5WeatherMode"><option value="yes">Live weather (when available)</option><option value="no">Skip live weather</option></select></label></div><div class="p5actions"><button class="p5btn" type="button" id="p5Build">🧭 Refine itinerary</button><button class="p5btn" type="button" id="p5Events">🎉 Show seasonal event</button><button class="p5btn" type="button" id="p5WeatherBtn">🌦️ Check weather</button></div><div class="p5out" id="p5Out"></div><div class="p5out" id="p5Weather"></div></div>';const result=document.getElementById('planResult');body.insertBefore(box,result||null);box.querySelector('#p5Build').onclick=renderEnhancedPlan;box.querySelector('#p5Events').onclick=()=>{const d=document.getElementById('p5Date')?.value||new Date().toISOString().slice(0,10),ev=eventData[monthIndex(d)],o=document.getElementById('p5Out');if(o){if(ev)o.innerHTML='<div class="p5card"><b>🎉 '+esc(ev[1])+'</b><div>'+esc(ev[2])+'</div><div class="p5muted">'+esc(ev[3])+'. Verify exact dates locally before travelling.</div></div>';else o.innerHTML='<div class="p5card"><b>🎉 Seasonal event guide</b><div class="p5muted">Select a valid start date to view the seasonal guide.</div></div>'}};box.querySelector('#p5WeatherBtn').onclick=weather;const original=window.makeAryaPlan;if(typeof original==='function'&&!original.__p5wrapped){const wrapped=async function(){const res=await original.apply(this,arguments);setTimeout(renderEnhancedPlan,80);return res};wrapped.__p5wrapped=true;window.makeAryaPlan=wrapped}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});
window.p5SavePlan=p5SavePlan;window.p5SharePlan=p5SharePlan;
})();